import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import { TABLE_ORGANIZATION_USERS, TABLE_ORGANIZATIONS } from "../constants";

const createOrganizationUsersQuery = (): QuerySqlToken<ZodTypeAny> => {
  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([TABLE_ORGANIZATION_USERS])} (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "role" VARCHAR(255),
      "organization_id" INTEGER NOT NULL,
      "user_id" VARCHAR(36) NOT NULL,
      FOREIGN KEY ("organization_id") REFERENCES 
        ${sql.identifier([TABLE_ORGANIZATIONS])} ("id")
        ON DELETE CASCADE
    );
  `;
};

export default createOrganizationUsersQuery;
