import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import { TABLE_ACCOUNTS } from "../constants";

const createOrganizationsQuery = (): QuerySqlToken<ZodTypeAny> => {
  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([TABLE_ACCOUNTS])} (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" VARCHAR(255),
      "slug" VARCHAR(255) UNIQUE,
      "organization_id" INTEGER NOT NULL
    );
  `;
};

export default createOrganizationsQuery;
