import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import { TABLE_ACCOUNT_USERS } from "../constants";

const createOrganizationsQuery = (): QuerySqlToken<ZodTypeAny> => {
  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([TABLE_ACCOUNT_USERS])} (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "account_id" INTEGER,
      "user_id" VARCHAR(36)
    );
  `;
};

export default createOrganizationsQuery;
