import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import { TABLE_ACCOUNT_USERS, TABLE_ACCOUNTS } from "../constants";

const createAccountUsersQuery = (): QuerySqlToken<ZodTypeAny> => {
  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([TABLE_ACCOUNT_USERS])} (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "account_id" INTEGER,
      "user_id" VARCHAR(36),
      FOREIGN KEY ("account_id") REFERENCES 
        ${sql.identifier([TABLE_ACCOUNTS])} ("id")
        ON DELETE CASCADE
    );
  `;
};

export default createAccountUsersQuery;
