import { QuerySqlToken, sql } from "slonik";

const queryToCreateTable: QuerySqlToken = sql.unsafe`
    DO $$
    BEGIN
        -- Check if the table exists
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'files') THEN
            CREATE TABLE files (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                original_file_name VARCHAR(255) NOT NULL,
                bucket VARCHAR(255) NOT NULL,
                description TEXT,
                key VARCHAR(255) NOT NULL,
                uploaded_by_id VARCHAR(255),
                uploaded_at TIMESTAMP,
                download_count INT DEFAULT 0,
                last_downloaded_at TIMESTAMP,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            );
        END IF;
    END $$;
`;

export default queryToCreateTable;
