const TABLE_PERMISSIONS = "permissions";
const TABLE_ROLES = "roles";
const TABLE_ROLE_PERMISSIONS = "role_permissions";
const TABLE_USER_ROLES = "users";

// Permissions
const ROUTE_PERMISSIONS = "/permissions";
const ROUTE_PERMISSIONS_CREATE = "/permissions";
const ROUTE_PERMISSIONS_DELETE = "/permissions/:id";
const ROUTE_PERMISSIONS_GET_BY_ID = "/permissions/:id";
const ROUTE_PERMISSIONS_UPDATE = "/permissions/:id";
// Roles
const ROUTE_ROLES = "/roles";
const ROUTE_ROLES_CREATE = "/roles";
const ROUTE_ROLES_DELETE = "/roles/:id";
const ROUTE_ROLES_GET_BY_ID = "/roles/:id";
const ROUTE_ROLES_UPDATE = "/roles/:id";

export {
  TABLE_ROLES,
  TABLE_ROLE_PERMISSIONS,
  TABLE_USER_ROLES,
  TABLE_PERMISSIONS,
  ROUTE_PERMISSIONS,
  ROUTE_PERMISSIONS_CREATE,
  ROUTE_PERMISSIONS_DELETE,
  ROUTE_PERMISSIONS_GET_BY_ID,
  ROUTE_PERMISSIONS_UPDATE,
  ROUTE_ROLES,
  ROUTE_ROLES_CREATE,
  ROUTE_ROLES_DELETE,
  ROUTE_ROLES_GET_BY_ID,
  ROUTE_ROLES_UPDATE,
};
