import { ApiConfig } from "@dzangolab/fastify-config";
import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import { TABLE_MODEL_ROLES } from "../constants";

const createModelRolesTableQuery = (
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  config: ApiConfig
): QuerySqlToken<ZodTypeAny> => {
  const tableName = TABLE_MODEL_ROLES;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([tableName])} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      model_id INTEGER NOT NULL,
      model_name VARCHAR(255) NOT NULL,
      role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    );
`;
};

export default createModelRolesTableQuery;
